import React, { useMemo } from 'react';
import { PhraseSchema } from '@/types/video';

interface TranscriptViewerProps {
  phrases: PhraseSchema[];
  currentTime: number;
  source: "transcript" | "captions" | "auto_captions" | null;
  isAutoGenerated: boolean;
  warning?: string;
  onPhraseClick: (index: number, startTime: number) => void;
  practiceMode: boolean;
  onPracticeToggle: () => void;
}

export function TranscriptViewer({
  phrases,
  currentTime,
  source,
  isAutoGenerated,
  warning,
  onPhraseClick,
  practiceMode,
  onPracticeToggle,
}: TranscriptViewerProps) {

  // Helper to get source label and styling
  const getSourceInfo = () => {
    switch (source) {
      case "transcript":
        return {
          icon: "📝",
          label: "Official Transcript",
          color: "text-green-600",
          bgColor: "bg-green-50",
          borderColor: "border-green-200",
          tooltip: "Full speech transcription - excellent for learning"
        };
      case "captions":
        return {
          icon: "📺",
          label: "Captions",
          color: "text-blue-600",
          bgColor: "bg-blue-50",
          borderColor: "border-blue-200",
          tooltip: "Official captions from the video creator"
        };
      case "auto_captions":
        return {
          icon: "🤖",
          label: "Auto-generated Captions",
          color: "text-yellow-600",
          bgColor: "bg-yellow-50",
          borderColor: "border-yellow-200",
          tooltip: "Automatically generated - may contain errors but great for practice!"
        };
      default:
        return {
          icon: "❓",
          label: "Unknown",
          color: "text-gray-600",
          bgColor: "bg-gray-50",
          borderColor: "border-gray-200",
          tooltip: "Unknown source"
        };
    }
  };

  const sourceInfo = useMemo(() => getSourceInfo(), [source]);

  // Find current phrase being spoken
  const currentPhraseIndex = useMemo(() => {
    return phrases.findIndex(
      phrase =>
        currentTime >= phrase.start_time &&
        currentTime < phrase.start_time + (phrase.duration || 0)
    );
  }, [currentTime, phrases]);

  // Format time helper
  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="w-full h-full flex flex-col bg-white rounded-lg shadow-sm">

      {/* Header with source info */}
      <div className={`px-4 py-3 border-b-2 ${sourceInfo.borderColor}`}>
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <span className="text-xl">{sourceInfo.icon}</span>
            <span className={`font-semibold text-sm ${sourceInfo.color}`}>
              {sourceInfo.label}
            </span>
          </div>

          {/* Info tooltip */}
          <div className="group relative">
            <button className="text-gray-400 hover:text-gray-600 text-sm">
              ℹ️
            </button>
            <div className="invisible group-hover:visible absolute right-0 top-8 bg-gray-900 text-white text-xs rounded py-2 px-3 z-50 w-48 whitespace-normal">
              {sourceInfo.tooltip}
            </div>
          </div>
        </div>

        {/* Warning for auto-generated */}
        {isAutoGenerated && warning && (
          <div className="mt-2 bg-yellow-100 border-l-4 border-yellow-400 p-2">
            <p className="text-xs text-yellow-800">
              <span className="font-semibold">⚠️ Auto-generated:</span> {warning}
            </p>
          </div>
        )}
      </div>

      {/* Phrases list - scrollable */}
      <div className="flex-1 overflow-y-auto px-4 py-3">
        {phrases && phrases.length > 0 ? (
          <div className="space-y-2">
            {phrases.map((phrase, index) => {
              const isCurrentPhrase =
                currentTime >= phrase.start_time &&
                currentTime < phrase.start_time + (phrase.duration || 0);

              const isPastPhrase = currentTime >= (phrase.start_time + (phrase.duration || 0));

              return (
                <div
                  key={index}
                  onClick={() => onPhraseClick(index, phrase.start_time)}
                  className={`
                    p-3 rounded-lg cursor-pointer transition-all duration-200
                    ${isCurrentPhrase
                      ? 'bg-blue-100 border-l-4 border-blue-500 shadow-sm'
                      : isPastPhrase
                      ? 'bg-gray-50 opacity-70'
                      : 'hover:bg-gray-100'
                    }
                  `}
                >
                  <div className="flex justify-between items-start gap-2">
                    {/* Phrase number and timestamp */}
                    <div className="min-w-fit">
                      {!practiceMode && (
                        <p className="text-gray-500 text-xs font-medium">
                          {formatTime(phrase.start_time)}
                        </p>
                      )}
                      <p className="text-gray-400 text-xs">
                        {index + 1}
                      </p>
                    </div>

                    {/* Phrase text */}
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 break-words">
                        {phrase.text}
                      </p>
                    </div>

                    {/* Playback indicator */}
                    {isCurrentPhrase && (
                      <span className="text-blue-500 text-lg">▶️</span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="flex items-center justify-center h-full text-gray-500">
            <p className="text-center">No phrases available</p>
          </div>
        )}
      </div>

      {/* Footer with practice mode toggle */}
      <div className="border-t px-4 py-2">
        <button
          onClick={onPracticeToggle}
          className={`
            w-full px-3 py-2 rounded text-sm font-medium transition-colors
            ${practiceMode
              ? 'bg-purple-500 text-white hover:bg-purple-600'
              : 'bg-gray-200 text-gray-800 hover:bg-gray-300'
            }
          `}
        >
          {practiceMode ? '👁️ Practice Mode ON (hide text)' : '📖 Normal Mode (show text)'}
        </button>
      </div>
    </div>
  );
}

export default TranscriptViewer;
